### ISSUE TITLE
How can I hide match field table ?

### ISSUE THREAD

**Issue by fralps** [jgile/vue-csv-import#44]
Hi 👋  !
I am pretty new to Vue JS and would like to know how to hide the fields matching table, because I don't want it: 

![Capture d’écran 2020-07-22 à 18 03 00](https://user-images.githubusercontent.com/48285890/88200175-19273b80-cc46-11ea-83fe-2d00ab143d1a.png)

Here are my props: 
`<vue-csv-import
          v-model="parseCsv"
          :map-fields="['email', 'firstname', 'lastname']"
          :auto-match-fields="true"
          :headers="true"
        />`

Thanks 😊

**Comment by jamby1100** [comment]
Hi fralps, I'm not the author of this package but I did find a way to do this that I would like to share.

I intentionally added the function disableMappingTable in the @click.prevent of the load button. See below:
```html
<vue-csv-import
    v-model="csv"
    url="/hello"
    :map-fields="['name', 'age']">

    <template slot="hasHeaders" slot-scope="{headers, toggle}">
        <label>
            <input type="checkbox" id="hasHeaders" :value="headers" @change="toggle">
            Headers?
        </label>
    </template>

    <template slot="error">
        File type is invalid
    </template>

    <template slot="thead">
        <tr>
            <th>My Fields</th>
            <th>Column</th>
        </tr>
    </template>

    <template slot="next" slot-scope="{load}">
        <button  @click.prevent="load() something()">load!</button>
    </template>

    <template slot="submit" slot-scope="{submit}">
        <button @click.prevent="submit" v-show="displaySubmitButton">send!</button>
    </template>
</vue-csv-import>
```

Then, in the JS, I have a method `disableMappingTable`. It manually sets the class of the mapping table (`vue-csv-uploader-part-two`) to have the display=none. Since the `disableMappingTable` comes after `load`, we get to overwrite whatever style changes `load` did!

Not exactly the Vue way, but works for me! I'm pretty sure there's a more Vue way of doing this with refs (just didnt know how since `vue-csv-uploader-part-two` is inside the package!!)

```js
export default {
  data: function() {
    return {
      displaySubmitButton: false
    }
  },
  methods: {
    disableMappingTable() {
      document.querySelector('.vue-csv-uploader-part-two').style.display =
        'none'
      this.displaySubmitButton = true
      console.log('something occured')
    },
}
```

As an added bonus, I only show the submit button when the user presses LOAD. Hope that makes sense!
